---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-home-cluster-l2-policy
spec:
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchLabels: {}
  interfaces:
  - ^enp0s8$
  externalIPs: true
  loadBalancerIPs: true
